name: karmalab_assignment
description: A new Flutter project.



publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter  
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  google_fonts: ^3.0.1
  remix: ^0.0.1-dev.1
  remixicon: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logos/
    -  assets/images/png/onboarding-images/
    -  assets/images/png/


  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
